class STATUS_BYTES(object):
    CAM_OK = 0x00
    CAM_NOT_READY = 0x02
    CAM_RANGE_ERROR = 0x03
    CAM_CHECKSUM_ERROR = 0x04
    CAM_UNDEFINED_PROCESS_ERROR = 0x05
    CAM_UNDEFINED_FUNCTION_ERROR = 0x06
    CAM_TIMEOUT_ERROR = 0x07
    CAM_BYTE_COUNT_ERROR = 0x09
    CAM_FEATURE_NOT_ENABLED = 0x0A